### ISSUE TITLE
Wrong Param Type for `get_col()`

### ISSUE THREAD

**Issue by szepeviktor** [wp-oop/transient-cache#11]
in `CachePool::selectColumn()`

```php
$this->wpdb->get_col($query, $columnName);
```

get_col expects an integer, not a string :(
https://developer.wordpress.org/reference/classes/wpdb/get_col/

`phpstan.neon.dist`

```yaml
includes:
    - vendor/szepeviktor/phpstan-wordpress/extension.neon
parameters:
# TODO    level: max
    level: 5
    inferPrivatePropertyTypeFromConstructor: true
    paths:
        - src/
```
